"""seasons bonuses users main_products

Revision ID: 7d380a9c3130
Revises: 7de867fe907c
Create Date: 2026-08-14 20:17:59.365510

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7d380a9c3130'
down_revision: str | None = '7de867fe907c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bonus_id', sa.String(length=64), nullable=False),
    sa.Column('season_id', sa.String(length=64), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('pdf_link', sa.Text(), nullable=False),
    sa.Column('audio_link', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bonuses_bonus_id'), ['bonus_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_bonuses_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonuses_season_id'), ['season_id'], unique=False)

    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.String(length=64), nullable=False),
    sa.Column('season_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('audio_link', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_episode_id'), ['episode_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_episodes_season_id'), ['season_id'], unique=False)

    op.create_table('main_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('season_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_subscriber', sa.Integer(), nullable=False),
    sa.Column('payment_link', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('main_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_main_products_product_id'), ['product_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_main_products_season_id'), ['season_id'], unique=False)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_subscriber', sa.Integer(), nullable=False),
    sa.Column('archive_link', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasons_season_id'), ['season_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('subscription_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchased_seasons', sa.JSON(), nullable=False),
    sa.Column('got_voice_demo', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tg_id'), ['tg_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tg_id'))

    op.drop_table('users')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_season_id'))
        batch_op.drop_index(batch_op.f('ix_seasons_is_current'))

    op.drop_table('seasons')
    with op.batch_alter_table('main_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_products_season_id'))
        batch_op.drop_index(batch_op.f('ix_main_products_product_id'))

    op.drop_table('main_products')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_season_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_episode_id'))

    op.drop_table('episodes')
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bonuses_season_id'))
        batch_op.drop_index(batch_op.f('ix_bonuses_keyword'))
        batch_op.drop_index(batch_op.f('ix_bonuses_bonus_id'))

    op.drop_table('bonuses')
    # ### end Alembic commands ###
